# Generated by Django 4.1.7 on 2023-03-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('idBranch', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=45)),
                ('assets', models.FloatField(max_length=11)),
                ('region', models.IntegerField()),
            ],
            options={
                'db_table': 'branch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('idLoan', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('quantity', models.FloatField(max_length=11)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'loan',
                'managed': False,
            },
        ),
    ]
