# Generated by Django 4.1.7 on 2023-03-20 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('idBranch', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=45)),
                ('assets', models.IntegerField()),
                ('region', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('idLoan', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('idBranch', models.ForeignKey(db_column='idBranch', on_delete=django.db.models.deletion.DO_NOTHING, to='users.branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
