# Generated by Django 4.1.7 on 2023-03-21 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_loan_idloan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='idBranch',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
