# Generated by Django 4.1.7 on 2023-03-28 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_loan_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='branch',
            table='global_branch',
        ),
    ]
